# server
server:
  port: 9090
  servlet:
    context-path: /${spring.application.name}

# logger 日志
logging:
  level:
    com: DEBUG
  config: classpath:config/logback.xml
  path: /ty/logs/interface

spring:
  application:
    name: ty
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

    #druid datasource configuration
  datasource:
    druid:
      enable: true
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 10
      max-active: 20
      min-idle: 10
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      validation-query: select 1 from dual
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 10
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /*.js,/*.gif,/*.jpg,/*.png,/*.css,/*.ico,/druid/*
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
        reset-enable: false
      filter:
        stat:
          enabled: true
          slow-sql-millis: 3000
          merge-sql: false
          log-slow-sql: true