# server
server:
  port: 9090
  servlet:
    context-path: /${spring.application.name}

# logger 日志
logging:
  config: classpath:config/logback.xml
  path: /ty/logs/interface

spring:
  application:
    name: ty
  profiles:
    active: product
  #彩色日志输出
  output:
    ansi:
      enabled: detect
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    #druid datasource configuration
    druid:
      enable: true
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 10
      max-active: 20
      min-idle: 10
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      validation-query: select 1 from dual
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 10
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /*.js,/*.gif,/*.jpg,/*.png,/*.css,/*.ico,/druid/*
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
        reset-enable: false
      filter:
        stat:
          enabled: true
          slow-sql-millis: 2000
          merge-sql: false
          log-slow-sql: true
  jpa:
    open-in-view: true
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  redis:
    jedis:
      pool:
        max-active: 20
        max-wait: 2000
        max-idle: 10
        min-idle: 0
    timeout: 0

mybatis-plus:
  mapper-locations: classpath:/com/ty/*/mapper/*Mapper.xml
  # 支持统配符 * 或者 ; 分割
  typeEnumsPackage: com.ty.enums
  typeAliasesPackage: com.ty.*.entity
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
