# server
server:
  port: 9090
  servlet:
    context-path: /ty

logging:
  level:
    com: INFO

#druid datasource configuration
spring:
  datasource:
    url: jdbc:mysql://106.13.81.46:3306/application?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&tinyInt1isBit=false
    username: root
    password: ty1234