# server
server:
  port: 9090
  servlet:
    context-path: /ty

#druid datasource configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/application?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&tinyInt1isBit=false
    username: root
    password: root